#%RAML 1.0
title: dogdog_API
version: v1
baseUri: http://api.bensonzhi.co

uses:

types:
    baseId:
        type: integer
        required: true
        description: 唯一标识Id
    baseName:
        type: string
        required: true
        description: 名称
    basePhone:
        type: string
        required: true
        description: 手机号码
    baseDesc:
        type: string
        required: false
        description: 备注
    baseDate:
        type: datetime
        format: rfc3339
        description: 日期
    retdata:
        type: object
        required: true
        description: 返回的数据
    result:
        type: object
        description: 服务器返回的JSON对象
        properties:
            retcode:
                type: integer
                required: true
                description: 0是正常码，其他是非正常
            retmsg:
                type: string
                required: true
                description: 操作信息/错误信息
    exist:
        type: result
        additionalProperties: true
        properties:
            retdata:
                type: integer
                description: 是否，1 - 是，0 - 否
    successId:
        type: result
        additionalProperties: true
        properties:
            retdata:
                type: integer
                required: true
                description: 新增的Id

traits:

/v1:
    description: v1.0
    displayName: v1.0
    /token:
        description: 获取 XSRF_COOKIES, 用于验证POST的跨域请求,在headers加上{"X-XSRFToken": "xxxxxx"}
        get:
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "xxxxxxxxxxx"
                                }
    /chn/signup:
        description: 下游注册
        post:
            queryParameters:
                username:
                    type        : string
                    description : 用户名
                    required    : true
                passwd:
                    type        : string
                    description : 密码
                    required    : true
                email:
                    type        : string
                    description : 邮箱
                    required    : true
                contact:
                    type        : string
                    description : 联系方式
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "username": "mao",
                            "passwd": "mao",
                            "email": "mao@mao.com",
                            "contact": "15988888888"
                        }
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    'retcode': 0,
                                    'retdata': {
                                        'chn_id': 'xxxxxxx'
                                    },
                                    'retmsg': 'success'
                                }
    /chn/login:
        description: 下游登录验证
        post:
            queryParameters:
                username:
                    type        : string
                    description : 用户名
                    required    : true
                passwd:
                    type        : string
                    description : 密码
                    required    : true

            body:
              application/json:
                  example: |
                      {
                          "username": "keita",
                          "passwd": "keita123",
                      }
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    'retcode': 0,
                                      'retdata': {
                                          'chn_id': 'xxxxxx',
                                      },
                                      'retmsg': 'success'
                                }
    /app/setting:
        description: 下游录入 callback_url后自动获取 token
        post:
            queryParameters:
                chn_id:
                    type        : string
                    description : 下游ID
                    required    : true
                app_id:
                    type        : string
                    description : APPID
                    required    : true
                callback_url:
                      type        : string
                      description : 回调地址
                      required    : true
            body:
                application/json:
                    example: |
                        {
                            "chn_id" : "xxxxxx",
                            "app_id" : "xxxxxx",
                            "callback_url" : "xxxxxx"
                        }
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    'retcode': 0,
                                    'retdata': {
                                        'AppSign': sign
                                    },
                                    'retmsg': 'success'
                                }

    /app/create:
        description: 下游提交创建 APP
        post:
            queryParameters:
                chn_id:
                  type        : string
                  description : 下游唯一ID
                  required    : true
                app_name:
                    type        : string
                    description : app名称
                    required    : true
                pkg_name:
                    type        : string
                    description : 包名称
                    required    : true
                category:
                    type        : string
                    description : 类型
                    required    : true
                platform:
                    type        : string
                    description : 平台
                    required    : true
                url:
                    type        : string
                    description : url
                    required    : true
                description:
                    type        : string
                    description : url
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "channeler_id": "DbcMXzmk",
                            "app_name": "test",
                            "pkg_name": "com.test.com",
                            "category": "xxxx",
                            "platform": "xxxx",
                            "url": "['xxxxx']",
                            "description": "xxxxx"
                        }
            responses:
                200:
                    body:
                        application/json:
                          example: |
                            {
                                'retcode': 0,
                                'retdata': {
                                    'AppID': app_id,
                                    'AppSecret': app_secret
                                  },
                                'retmsg': 'APP is created,please contract your account manager to active your APP',
                            }
    /app/active:
        description: 激活下游APP
        post:
            queryParameters:
                app_id:
                    type        : string
                    description : app_id
                    required    : true
                chn_id:
                    type        : string
                    description : channeler_id
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "app_id": "xxxxx",
                            "chn_id": "xxxxx"
                        }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retmsg": "APP active successfully",
                                }
    /app/detail:
        description: 获取APP详情
        post:
            queryParameters:
                app_id:
                    type        : string
                    description : app_id
                    required    : true
                chn_id:
                    type        : string
                    description : channeler_id
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "app_id": "xxxxx",
                            "chn_id": "xxxxx"
                        }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retdata": {
                                        "app_id": "azLCKhW98M3E5AUk",
                                        "app_name": "mysql",
                                        "app_secret": "MBQTVbMgY6Iy81dPmheWQg==",
                                        "pkg_name": "com.mysql.com",
                                        "platform": "IOS",
                                        "status": 1
                                    },
                                    "retmsg": "success",
                                }
    /app/list:
        description: 获取当前下游的所有APP详情
        post:
            queryParameters:
                chn_id:
                    type        : string
                    description : channeler_id
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "chn_id": "xxxxx"
                        }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retdata": [
                                        {
                                            "app_id": "azLCKhW98M3E5AUk",
                                            "app_name": "mysql",
                                            "app_secret": "MBQTVbMgY6Iy81dPmheWQg==",
                                            "pkg_name": "com.mysql.com",
                                            "platform": "IOS",
                                            "status": 1
                                        },
                                        {
                                            "app_id": "tYpInTNS3jdxiol5",
                                            "app_name": "zeropark",
                                            "app_secret": "/9hCnnp+FzjLu64u+ONT3g==",
                                            "pkg_name": "com.zeropark.com",
                                            "platform": "Android",
                                            "status": 1
                                        }
                                    ],
                                    "retmsg": "success",
                                }
    /am/login:
        description: AM登录验证
        post:
            queryParameters:
                username:
                    type        : string
                    description : username
                    required    : true
                password:
                    type        : string
                    description : password
                    required    : true
            body:
                application/json:
                    example: |
                        {
                            "username": "Chen",
                            "passwd": "admin"
                        }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    'retcode': 0,
                                    'retdata': {
                                        'am_id': xx,
                                        'is_logined': 1,
                                    },
                                    'retmsg': 'success'
                                }

    /am/multioffer:
        description: 为下游创建OFFER
        post:
            queryParameters:
                app_id:
                    type        : string
                    description : app_id
                    required    : true
                chn_id:
                    type        : string
                    description : channeler_id
                    required    : true
                rule_id:
                    type        : string
                    description : rule_id
                    required    : true
            body:
                application/json:
                example: |
                    {
                        "app_id": "xxxxx",
                        "chn_id": "xxxxx",
                        "rule_id": 2
                    }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retmsg": "Offer create successfully",
                                }
    /am/connchn:
        description:  更改下游账号状态
        post:
            queryParameters:
                status:
                    type        : string
                    description : app_id
                    required    : true
                chn_id:
                    type        : string
                    description : chn_id
                    required    : true
            body:
                application/json:
                example: |
                    {
                        "status": 1,
                        "am_id": 1,
                        "chn_id": "xxxxx",
                    }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retmsg": "channeler status update successfully",
                                }
    /ad/getAdIDlist:
        description:  获取该联盟下的所有广告
        post:
            queryParameters:
                ader_id:
                    type        : int
                    description : ader_id
                    required    : true

            body:
                application/json:
                example: |
                    {
                        "ader_id": 1,
                    }
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retdata": [
                                        {
                                            "name/联盟名称": "有米",
                                            "ad_name/广告名": "foodpanda - Order Food Delivery for Pizza, Burger",
                                            "pkg_name/包名": "758103884",
                                            "region/投放地区": "[u'HK']",
                                            "get_price/广告主出价": 1.52,
                                            "put_price/下放价": 0,
                                            "access_price/成本价": 0,
                                            "click/有效点击数": 0,
                                            "installed/安装数": 0,
                                            "income/我方收入": 0
                                          },
                                        {
                                            "name": "有米",
                                            "ad_name": "Space Manager",
                                            "pkg_name": "com.mobileartsme.spacemanager",
                                            "region": "[u'AE']",
                                            "get_price": 0.95,
                                            "put_price": 0,
                                            "access_price": 0,
                                            "click": 0,
                                            "installed": 0,
                                            "income": 0
                                          },
                                        ]
                                    "retmsg": "success",
                                }
    /ad/getAdAll:
        description:  获取所有联盟下的所有广告
        post:
            responses:
                200:
                    body:
                        application/json:
                            type: exist
                            example: |
                                {
                                    "retcode": 0,
                                    "retdata": [
                                        {
                                            "name/联盟名称": "有米",
                                            "ad_name/广告名": "foodpanda - Order Food Delivery for Pizza, Burger",
                                            "pkg_name/包名": "758103884",
                                            "region/投放地区": "[u'HK']",
                                            "get_price/广告主出价": 1.52,
                                            "put_price/下放价": 0,
                                            "access_price/成本价": 0,
                                            "click/有效点击数": 0,
                                            "installed/安装数": 0,
                                            "income/我方收入": 0
                                        },
                                        {
                                            "name": "有米",
                                            "ad_name": "Space Manager",
                                            "pkg_name": "com.mobileartsme.spacemanager",
                                            "region": "[u'AE']",
                                            "get_price": 0.95,
                                            "put_price": 0,
                                            "access_price": 0,
                                            "click": 0,
                                            "installed": 0,
                                            "income": 0
                                        },
                                      ]
                                      "retmsg": "success",
                                }
